#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 19, 2018 06:15:03 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import project_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    project_support.set_Tk_var()
    top = New_Toplevel (root)
    project_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    project_support.set_Tk_var()
    top = New_Toplevel (w)
    project_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font13 = "-family {DejaVu Sans} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1440x846+1440+0")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")



        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.05, rely=0.04, relheight=0.94
                , relwidth=0.92)
        self.TNotebook1.configure(width=1322)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Roll Call", compound="left", underline="-1"
                ,)
        self.TNotebook1_t0.configure(width=1350)
        self.TNotebook1_t1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Exam Mode", compound="left", underline="-1"
                ,)

        self.Frame1 = Frame(self.TNotebook1_t0)
        self.Frame1.place(relx=0.07, rely=0.13, relheight=0.84, relwidth=0.88)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#e2ffe0")
        self.Frame1.configure(highlightbackground="#4f4f4f")
        self.Frame1.configure(width=1165)

        self.Button4 = Button(self.Frame1)
        self.Button4.place(relx=0.01, rely=0.02, height=65, width=175)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(background="#ffffd6")
        self.Button4.configure(text='''Button''')
        self.Button4.configure(width=117)

        self.Button4_1 = Button(self.Frame1)
        self.Button4_1.place(relx=0.01, rely=0.12, height=65, width=175)
        self.Button4_1.configure(activebackground="#d9d9d9")
        self.Button4_1.configure(background="#ffffd6")
        self.Button4_1.configure(text='''Button''')

        self.Button4_2 = Button(self.Frame1)
        self.Button4_2.place(relx=0.01, rely=0.23, height=65, width=175)
        self.Button4_2.configure(activebackground="#d9d9d9")
        self.Button4_2.configure(background="#ffffd6")
        self.Button4_2.configure(text='''Button''')

        self.Button4_2 = Button(self.Frame1)
        self.Button4_2.place(relx=0.01, rely=0.34, height=65, width=175)
        self.Button4_2.configure(activebackground="#d9d9d9")
        self.Button4_2.configure(background="#ffffd6")
        self.Button4_2.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.01, rely=0.45, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.01, rely=0.56, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.01, rely=0.67, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.01, rely=0.78, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.01, rely=0.88, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.16, rely=0.02, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.16, rely=0.12, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.16, rely=0.23, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.16, rely=0.34, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.16, rely=0.45, height=65, width=175)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(background="#ffffd6")
        self.Button4_3.configure(text='''Button''')

        self.Button4_3 = Button(self.Frame1)
        self.Button4_3.place(relx=0.0, rely=0.0, height=1, width=1)
        self.Button4_3.configure(activebackground="#d9d9d9")
        self.Button4_3.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.16, rely=0.56, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')
        self.Button4_4.configure(width=117)

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.16, rely=0.67, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.16, rely=0.78, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')
        self.Button4_4.configure(width=117)

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.16, rely=0.88, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.02, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.12, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.23, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.34, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.45, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.56, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.67, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.78, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.35, rely=0.88, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.02, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.12, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.23, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.34, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.45, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.56, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.67, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.78, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.51, rely=0.88, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.02, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.02, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.12, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.23, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.34, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.45, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.56, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.67, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.78, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.69, rely=0.88, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.12, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.23, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.34, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.45, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.56, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.67, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.78, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.Button4_4 = Button(self.Frame1)
        self.Button4_4.place(relx=0.84, rely=0.88, height=65, width=175)
        self.Button4_4.configure(activebackground="#d9d9d9")
        self.Button4_4.configure(background="#ffffd6")
        self.Button4_4.configure(text='''Button''')

        self.tNo40_t0_but41 = Button(self.TNotebook1_t0)
        self.tNo40_t0_but41.place(relx=0.54, rely=0.04, height=46, width=120)
        self.tNo40_t0_but41.configure(activebackground="#d9d9d9")
        self.tNo40_t0_but41.configure(text='''Edit Student list''')
        self.tNo40_t0_but41.configure(width=97)

        self.Button1_5 = Button(self.TNotebook1_t0)
        self.Button1_5.place(relx=0.65, rely=0.04, height=46, width=107)
        self.Button1_5.configure(activebackground="#d9d9d9")
        self.Button1_5.configure(text='''Student Info''')

        self.Button1_6 = Button(self.TNotebook1_t0)
        self.Button1_6.place(relx=0.86, rely=0.04, height=46, width=110)
        self.Button1_6.configure(activebackground="#fdffbd")
        self.Button1_6.configure(activeforeground="#ffa1a1")
        self.Button1_6.configure(background="#ffa1a1")
        self.Button1_6.configure(font=font13)
        self.Button1_6.configure(foreground="#fdffbd")
        self.Button1_6.configure(text='''Re - Roll Call''')

        self.Button1_6 = Button(self.TNotebook1_t0)
        self.Button1_6.place(relx=0.76, rely=0.04, height=46, width=107)
        self.Button1_6.configure(activebackground="#d9d9d9")
        self.Button1_6.configure(text='''Absent List''')

        self.TCombobox1 = ttk.Combobox(self.TNotebook1_t0)
        self.TCombobox1.place(relx=0.07, rely=0.05, relheight=0.02
                , relwidth=0.45)
        self.TCombobox1.configure(textvariable=project_support.combobox)
        self.TCombobox1.configure(width=597)
        self.TCombobox1.configure(background="#000000")
        self.TCombobox1.configure(takefocus="")

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()



